### ISSUE TITLE
Can you add zebrafish support to CAST-Seq ?

### ISSUE THREAD

**Issue by SeqCrafter** [gandrigit/Papers#1]
Hi gandrigit,

I saw that currently Cast-Seq has human and mouse genomes in it. Can you help with zebrafish, which is a type of popular model animal used in Crispr editing? I commit issues on CAST-seq reposity but there is no response over three months.

**Comment by ukf-andrieux** [comment]
Dear Xiaoguang,
I just answered in the proper repository so I will close this issue.
